config/routes.rb
# frozen_string_literal: true

Cpc::Application.routes.draw do

  constraints AdminConstraint do
    mount Flipper::UI.app(Flipper) => '/flipper'
  end

  constraints InternalUserConstraint do
    root to: 'internal/dashboards#show'
  end

  constraints CustomerUserConstraint do
    resources :customers do
      resources :work_orders, only: [:show], controller: 'customers/work_orders'
    end

    root to: 'customers/dashboards#show'
  end

  resources :boxes
  resources :colors
  resources :contacts
  resources :customers do
    resources :attachments, only: [:create]
    resources :contacts
    resources :notes
    resources :users, controller: 'customers/users'
      resources :work_orders
  end
  resources :manufacturers
  resources :notes
  resources :powders
  resources :quote_requests do
    resources :notes

    member do
      get 'mark_as_viewed'
      get 'mark_as_submitted'
      get 'mark_as_won'
      get 'mark_as_lost'
    end

    collection do
      get 'calculator'
      get 'sand_blasting_quote_calculator'
    end

    resources :quotes
  end
  resources :quote_request_attachments
  resource :quote_request_conversions, only: [:create]
  resources :service_schedules
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/thank_you'
  devise_for :users
  resources :users
  resources :work_orders do
    resources :attachments, only: [:create]
    resources :notes

    collection do
      get :workflow
    end

    member do
      post :quality_assurance_approval
      put :mark_completed
    end
  end
  resources :work_order_schedules

  root to: 'static_pages#home'
end

app/models/quote_request.rb
# frozen_string_literal: true

require 'csv'

class QuoteRequest < ApplicationRecord
  has_many :quote_request_attachments
  accepts_nested_attributes_for :quote_request_attachments
  has_many :notes, as: :notable
  has_one :work_order
  has_many :quotes

  belongs_to :user
  belongs_to :customer

  SOURCES = ['Word Of Mouth', 'Online Search', 'Social Media'].freeze
  STATUSES = %w[New Viewed Submitted Won Lost].freeze

  def self.to_csv
    CSV.generate do |csv|
      csv << ['created at', 'first name', 'last name', 'phone', 'email', 'job title', 'customer id', 'customer name', 'employee email', 'employee id', 'status', 'source']
      all.each do |quote_request|
        csv << [quote_request.created_at&.iso8601, quote_request.first_name, quote_request.last_name, quote_request.telephone, quote_request.email, quote_request.job_title, quote_request.customer_id, quote_request.customer&.name, quote_request.user&.email, quote_request.user_id, quote_request.status, quote_request.source]
      end
    end
  end
end

app/controllers/quote_requests_controller.rb
# frozen_string_literal: true

class QuoteRequestsController < ApplicationController
  before_action :authenticate_user!, except: %i[new create]

  # GET /quotes
  # GET /quotes.json
  def index
    @active_quote_requests = QuoteRequest.where('status = ? OR status = ? OR status = ?', 'New', 'Viewed', 'Submitted')
    @quote_requests = QuoteRequest.order('created_at DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quote_requests }
      format.csv { send_data @quote_requests.to_csv, filename: "quote-requests-#{Date.today}.csv" }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote_request = QuoteRequest.includes(notes: :user).find(params[:id])
    @notes = @quote_request.notes.page(params[:page])
    @note = @notes.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote_request = QuoteRequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote_request }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote_request = QuoteRequest.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote_request = QuoteRequest.new(quote_request_params)

    respond_to do |format|
      if (verify_recaptcha(model: @quote_request) || Rails.env.development? || current_user) && @quote_request.save
        process_attachments
        NotificationMailer.new_quote(@quote_request).deliver unless current_user || Rails.env.development?
        # Redirect to thank you page with request_type in params
        format.html { redirect_to static_pages_thank_you_url(request_type: 'quote'), notice: 'Request received. We will contact you shortly.' }
        format.json { render json: @quote_request, status: :created, location: @quote_request }
      else
        flash[:error] = 'Please verify that you are not a robot by checking the checkbox below.' unless verify_recaptcha(model: @quote_request)
        format.html { render action: 'new' }
        format.json { render json: @quote_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote_request = QuoteRequest.find(params[:id])

    respond_to do |format|
      if @quote_request.update_attributes(quote_request_params)
        process_attachments
        format.html { redirect_to @quote_request, notice: 'RFQ was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quote_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote_request = QuoteRequest.find(params[:id])
    @quote_request.destroy

    respond_to do |format|
      format.html { redirect_to quote_requests_url }
      format.json { head :no_content }
    end
  end

  def calculator
    @powder_costs = [['stock', 10], ['exotic', 15], ['custom', 25]]
    @oven_sizes = { small: 35, large: 70 }
  end

  def sand_blasting_quote_calculator
    @powder_costs = [['stock', 10], ['exotic', 15], ['custom', 25]]
    @oven_sizes = { small: 35, large: 70 }
  end

  def mark_as_viewed
    @quote_request = QuoteRequest.find(params[:id])

    @quote_request.update_attribute :status, 'Viewed'

    redirect_to quote_requests_url, notice: 'Quote request has been marked as viewed.'
  end

  def mark_as_submitted
    @quote_request = QuoteRequest.find(params[:id])

    @quote_request.update_attribute :status, 'Submitted'

    redirect_to quote_requests_url, notice: 'Quote request has been marked as submitted.'
  end

  def mark_as_won
    @quote_request = QuoteRequest.find(params[:id])

    @quote_request.update_attribute :status, 'Won'

    redirect_to quote_requests_url, notice: 'Quote request has been marked as won.'
  end

  def mark_as_lost
    @quote_request = QuoteRequest.find(params[:id])

    @quote_request.update_attribute :status, 'Lost'

    redirect_to quote_requests_url, notice: 'Quote request has been marked as lost.'
  end

  def process_attachments
    return unless params[:quote_request_attachments]

    quote_request_attachement_params['attachment'].each do |a|
      @quote_request.quote_request_attachments.create!(attachment: a)
    end
  end

  private

  # Using a private method to encapsulate the permissible parameters
  # is just a good pattern since you'll be able to reuse the same
  # permit list between create and update. Also, you can specialize
  # this method with per-user checking of permissible attributes.
  def quote_request_params
    params.require(:quote_request).permit(:address_1, :address_2, :city, :coating_requirements, :company_name, :email, :fax, :first_name, :job_title, :last_name, :masking_requirements, :note, :packaging_requirements, :paint_specs, :part_description, :part_number, :part_size, :powder_color, :powder_product_code, :powder_product_manufacturer, :quantity_run, :quantity_year, :state, :substrate, :telephone, :zip, :status, :user_id, :source, :customer_id, notes_attributes: %i[user_id content])
  end

  def quote_request_attachement_params
    return unless params[:quote_request_attachments]
    params.require(:quote_request_attachments).permit(attachment: [])
  end
end

app/helpers/quote_requests_helper.rb
# frozen_string_literal: true

module QuoteRequestsHelper
  def us_states
    [
      %w[Alabama AL],
      %w[Alaska AK],
      %w[Arizona AZ],
      %w[Arkansas AR],
      %w[California CA],
      %w[Colorado CO],
      %w[Connecticut CT],
      %w[Delaware DE],
      ['District of Columbia', 'DC'],
      %w[Florida FL],
      %w[Georgia GA],
      %w[Hawaii HI],
      %w[Idaho ID],
      %w[Illinois IL],
      %w[Indiana IN],
      %w[Iowa IA],
      %w[Kansas KS],
      %w[Kentucky KY],
      %w[Louisiana LA],
      %w[Maine ME],
      %w[Maryland MD],
      %w[Massachusetts MA],
      %w[Michigan MI],
      %w[Minnesota MN],
      %w[Mississippi MS],
      %w[Missouri MO],
      %w[Montana MT],
      %w[Nebraska NE],
      %w[Nevada NV],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      %w[Ohio OH],
      %w[Oklahoma OK],
      %w[Oregon OR],
      %w[Pennsylvania PA],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      %w[Tennessee TN],
      %w[Texas TX],
      %w[Utah UT],
      %w[Vermont VT],
      %w[Virginia VA],
      %w[Washington WA],
      ['West Virginia', 'WV'],
      %w[Wisconsin WI],
      %w[Wyoming WY]
    ]
  end
end

app/views/quote_requests/_form.html.haml
- unless current_user
  .row
    .col-12
      .alert.alert-success.mb-4{:style => "padding:15px 20px 15px 20px;"}
        Submit a short description of your project, some pictures or plans (if you have them) and
        = succeed "." do
          %strong someone will get in touch within one business day
= simple_form_for(@quote_request) do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-12
        %h3{:style => "padding-top:10px; border-bottom: solid gray 1px;"} RFQ Information
        %p.mb-4
          %em
            If you have any issues submitting this form please email
            %a{:href => "mailto:paul@columbuspowdercoat.com"}
              paul@columbuspowdercoat.com
            or call us at (614) 300-5025.
    .row
      .col-sm-6
        = f.input :first_name
        = f.input :last_name
        = f.input :email
        = f.input :telephone
        = f.input :note, placeholder: "Description of project.", :input_html => { :rows => 5 }
        = f.input :source, collection: QuoteRequest::SOURCES,
          label: 'Tell us how you found us.',
          input_html: { class: 'chosen' }
        %p
          = f.fields_for :post_attachments do |p|
            .card.card-body
              .card-title
                %strong Add Attachments
              .card-text
                .field
                  You can include most popular file types. (PDF, JPEG, PNG, GIF)
                  %br/
                  = p.label :attachments, required: false
                  %br/
                  = p.file_field :attachment, multiple: true,
                    name: "quote_request_attachments[attachment][]"
        %div{:style => "margin-bottom:25px;"}
          = recaptcha_tags unless Rails.env.development? || current_user
        - if user_signed_in?
          = f.input :status, collection: QuoteRequest::STATUSES, input_html: { class: 'chosen' }
          - if !@quote_request.user || current_user.admin?
            = f.association :user, label_method: :email, input_html: { class: 'chosen' }
          - else
            = f.input :user, readonly: true, input_html: { value: @quote_request&.user.full_name }
          - if !@quote_request.customer || current_user.admin?
            = f.association :customer, label_method: :name, input_html: { class: 'chosen' }
          - else
            = f.input :customer, readonly: true, input_html: { value: @quote_request&.customer.name }

  .form-actions
    = f.submit "Submit Request", class: "btn btn-lg btn-success"

app/views/quote_requests/_quote_request_table.html.haml
.quote_request_table
  %table.datatable.display.no-wrap{:width => "100%"}
    %thead
      %tr
        %th Date
        %th Status
        %th First name
        %th Last name
        %th Email
        %th Telephone
        %th Assigned to
        %th.all
        %th
    %tbody
      - quote_requests.each do |qr|
        %tr
          %td= qr.created_at.strftime("%m/%d/%Y")
          %td= qr.status == "New" ? "<span class='badge badge-success'>New</span>".html_safe : qr.status
          %td= qr.first_name
          %td= qr.last_name
          %td= qr.email
          %td= qr.telephone
          %td= qr.user ? qr.user.full_name : 'Not assigned'
          %td= link_to 'Show', qr
          %td
            - if qr.status == "New"
              = link_to "Mark As Viewed", mark_as_viewed_quote_request_path(qr)
            - elsif qr.status == "Viewed"
              = link_to "Mark As Submitted", mark_as_submitted_quote_request_path(qr)
            - elsif qr.status == "Submitted"
              = link_to "Mark As Won", mark_as_won_quote_request_path(qr)
              %br/
              = link_to "Mark As Lost", mark_as_lost_quote_request_path(qr)

app/views/quote_requests/calculator.html.haml
.container
  .row
    .col-sm-12
      %h1.mb-4 Quote Calculator
  .row
    .col-sm-8
      = form_tag '#', onSubmit: "return false", id: 'calculator-form' do
        .row.mb-3
          .col-sm-6
            = label_tag 'Labor Hours'
            = text_field_tag :labor_hours, nil, placeholder: 'Estimated # of hours', class: 'form-control', data: { rate: 130 }
        .row.mb-3
          .col-sm-6
            = label_tag 'Oven Hours'
            = text_field_tag :oven_hours, nil, placeholder: 'Estimated # of hours', class: 'form-control'
          .col-sm-6
            = label_tag 'Oven Size'
            = select_tag :oven_size,
              options_from_collection_for_select(@oven_sizes, :last, :first),
              class: 'form-control'
        .row.mb-4
          .col-sm-6
            = label_tag 'Powder Pounds'
            = text_field_tag :powder_weight,
              nil,
              placeholder: 'Estimated # of lbs',
              class: 'form-control'
          .col-sm-6
            = label_tag 'Price per pound'
            = select_tag :powder_price,
              options_for_select([['Exotic ($18.75/lb.)', 18.75], ['Custom ($31.50/lb.)', 31.50]]),
              prompt: 'Select a powder price',
              class: 'form-control'
        .row.mt-3
          .col-lg-12.text-center.mb-2
            %label{:for => "margin"} Cost Of Business
            %br/
            %input{"data-provide" => "slider", "data-slider-max" => "8", "data-slider-min" => "0", "data-slider-step" => "1", "data-slider-ticks" => "[0, 1, 2, 3, 4, 5, 6, 7, 8]", "data-slider-ticks-labels" => "[\"IGT\", \"\", \"\", \"\", \"ITIGT\", \"\", \"\", \"\", \"IDHAFC\"]", "data-slider-tooltip" => "hide", "data-slider-value" => "2", :name => "cost-of-business", :type => "integer"}/
          .col-lg-12.text-center.mb-4
            %label{:for => "margin"} Pricing Scale
            %br/
            %input{"data-provide" => "slider", "data-slider-max" => "4", "data-slider-min" => "0", "data-slider-step" => "1", "data-slider-ticks" => "[0, 1, 2, 3, 4]", "data-slider-ticks-labels" => "[\"A\", \"B\", \"C\", \"R\", \"F\"]", "data-slider-tooltip" => "hide", "data-slider-value" => "0", :name => "margin", :type => "integer"}/
    / /.col-sm-8
    .col-sm-4
      %table.table.tabl-bordered
        %thead
          %tr
            %th Total
        %tbody
          %td#total
            $
            %span 0.00

app/views/quote_requests/edit.html.haml
.container.contact
  %h1{:style => "font-weight:200;"} Editing quote
  = render 'form'
  %p
    = link_to 'Show', @quote_request
    |
    \#{link_to 'Back', quote_requests_path}

app/views/quote_requests/index.html.haml
.container.contact
  .row
    .col-lg-12
      %h1 Quote Requests
      .mt-3.mb-3
        %strong Download:
        = link_to 'CSV', quote_requests_path(format: 'csv')
      .d-none.d-md-block.mt-4.mb-4
        = link_to 'New Quote Request', new_quote_request_path, class: "btn btn-success"
      .d-block.d-md-none.mt-4.mb-4
        = link_to 'New Quote Request', new_quote_request_path, class: "btn btn-success btn-block"
      - if params[:quote_request] == "All"
        %p= link_to "Active Quote Requests >", quote_requests_path
        = render 'quote_request_table', quote_requests: @quote_requests
      - else
        %p= link_to "All Quote Requests >", quote_requests_path(quote_request: "All")
        = render 'quote_request_table', quote_requests: @active_quote_requests

app/views/quote_requests/new.html.haml
.container
  .row
    .col-sm-12
      = render 'form'

app/views/quote_requests/sand_blasting_quote_calculator.html.haml
.container
  .row
    .col-sm-12
      %h1.mb-4 Sand Blasting Quote Calculator
  .row
    .col-sm-8
      = form_tag '#', onSubmit: "return false", id: 'sand-blasting-calculator-form' do
        .row.mb-3
          .col-sm-6
            = label_tag 'Labor Hours'
            = text_field_tag :labor_hours, nil, placeholder: 'Estimated # of hours', class: 'form-control', data: { rate: 100 }
        .row.mt-3
          .col-md-6.text-center.mb-4
            %label{:for => "margin"} Pricing Scale
            %br/
            %input{"data-provide" => "slider", "data-slider-max" => "4", "data-slider-min" => "0", "data-slider-step" => "1", "data-slider-ticks" => "[0, 1, 2, 3, 4]", "data-slider-ticks-labels" => "[\"A\", \"B\", \"C\", \"R\", \"F\"]", "data-slider-tooltip" => "hide", "data-slider-value" => "0", :name => "margin", :type => "integer"}/
    / /.col-sm-8
    .col-sm-4
      %table.table.tabl-bordered
        %thead
          %tr
            %th Total
        %tbody
          %td#total
            $
            %span 0.00

app/views/quote_requests/show.html.haml
.container.contact
  .row
    .col-md-4
      %p
        %b Quote Request #:
        = @quote_request.id
      %p
        %b Customer:
        - if @quote_request.customer
          = @quote_request.customer.name
        - else
          %span.text-danger Not Assigned
      %p
        %b First name:
        = @quote_request.first_name
      %p
        %b Last name:
        = @quote_request.last_name
      %p
        %b Email:
        = mail_to @quote_request.email
      %p
        %b Telephone:
        = @quote_request.telephone
      %p
        %b Note:
        = @quote_request.note
      %p
        %b Quote Request Owner:
        = @quote_request.user.try :full_name
      - if @quote_request.quote_request_attachments
        %p
          %b Attachments:
          - @quote_request.quote_request_attachments.each_with_index do |qra, i|
            = link_to "Attachment #{i+1}", qra.attachment.url
      = link_to 'Edit', edit_quote_request_path(@quote_request)
      | #{link_to "Generate Calcuation", calculator_quote_requests_path} | #{link_to 'Destroy', @quote_request, method: :delete, data: { confirm: 'Are you sure you want to delete this quote request?' }}
    .col-md-4
      %h2 Quotes
      %table.table.table-condensed.table-bordered
        %thead
          %tr
            %th
            %th Total
        %tbody
          - @quote_request.quotes.each_with_index do |quote, i|
            %tr
              %td= link_to "Quote #{ i+1 }", quote_request_quote_path(@quote_request, quote), target: '_blank'
              %td $#{number_with_precision quote.total, precision: 2}
      = link_to 'New Quote', new_quote_request_quote_path(@quote_request), target: :_blank

    .col-md-4.mt-md-0.mt-lg-0.mt-5
      .row.mb-3
        .col
          - if @quote_request.work_order
            = link_to 'View Work Order', @quote_request.work_order, class: 'btn btn-primary float-right'
          - else
            - if @quote_request.customer
              = link_to 'Convert To Work Order', quote_request_conversions_path(quote_request_id: @quote_request.id), method: :post, class: 'btn btn-warning float-right', data: { confirm: 'Are you sure? This will mark the current quote request as \'Won\' and will create a new work order assigned to this company.' }
            - else
              = button_to 'Convert To Work Order', {}, disabled: true, class: 'btn btn-warning float-right', title: 'Please add a customer to convert to a work order'
      .row
        .col
          %h2 Add Note
          = render partial: 'notes/notable_form', locals: { resource: @quote_request, note: @note}
      .row.mt-4
        .col.notes-index
          = render partial: 'notes/index_snippet', locals: { notes: @notes, page: params[:page] }