config/routes.rb
# frozen_string_literal: true

Cpc::Application.routes.draw do

  constraints AdminConstraint do
    mount Flipper::UI.app(Flipper) => '/flipper'
  end

  constraints InternalUserConstraint do
    root to: 'internal/dashboards#show'
  end

  constraints CustomerUserConstraint do
    resources :customers do
      resources :work_orders, only: [:show], controller: 'customers/work_orders'
    end

    root to: 'customers/dashboards#show'
  end

  resources :boxes
  resources :colors
  resources :contacts
  resources :customers do
    resources :attachments, only: [:create]
    resources :contacts
    resources :notes
    resources :users, controller: 'customers/users'
      resources :work_orders
  end
  resources :manufacturers
  resources :notes
  resources :powders
  resources :quote_requests do
    resources :notes

    member do
      get 'mark_as_viewed'
      get 'mark_as_submitted'
      get 'mark_as_won'
      get 'mark_as_lost'
    end

    collection do
      get 'calculator'
      get 'sand_blasting_quote_calculator'
    end

    resources :quotes
  end
  resources :quote_request_attachments
  resource :quote_request_conversions, only: [:create]
  resources :service_schedules
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/thank_you'
  devise_for :users
  resources :users
  resources :work_orders do
    resources :attachments, only: [:create]
    resources :notes

    collection do
      get :workflow
    end

    member do
      post :quality_assurance_approval
      put :mark_completed
    end
  end
  resources :work_order_schedules

  root to: 'static_pages#home'
end

app/models/quote.rb
# frozen_string_literal: true

class Quote < ApplicationRecord
  belongs_to :quote_request
  belongs_to :user

  def total
    coating_costs + total_sandblasting_cost
  end

  def labor_cost
    ((labor_hours || 0) * (labor_rate || Cpc::QuoteForm::LABOR_RATE)).to_f
  end

  def powder_cost
    return 0 unless powder_pounds
    (powder_pounds * (powder_price || Cpc::QuoteForm::POWDER_PRICES.first.last)).to_f
  end

  def oven_cost
    return 0 unless oven_hours
    (oven_hours * (hourly_oven_price || Cpc::QuoteForm::OVEN_SIZES[:small])).to_f
  end

  def sandblasting_media_cost
    (sandblasting_labor_cost * (sandblasting_media_multiplier || Cpc::QuoteForm::SANDBLASTING_MEDIA_MULTIPLIER)).to_f
  end

  def sandblasting_labor_cost
    return 0 unless sandblasting_hours
    (sandblasting_hours * sandblasting_rate).to_f
  end

  def coating_costs
    ((cost_of_business.to_f * soft_costs) + soft_costs) / margin_divisor
  end

  def total_sandblasting_cost
    (sandblasting_labor_cost + sandblasting_media_cost) / margin_divisor
  end

  def soft_costs
    (labor_cost + oven_cost + powder_cost).to_f
  end

  def margin_divisor
    (1.0.to_f - pricing_scale.to_f)
  end
end

app/controllers/quotes_controller.rb
# frozen_string_literal: true

class QuotesController < ApplicationController
  before_action :authenticate_user!, except: %i[new create]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote_form = Cpc::QuoteForm.new(quote_request, nil)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote_form = Cpc::QuoteForm.new(quote_request, quote)
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params.merge(quote_request_id: params[:quote_request_id]))

    respond_to do |format|
      if @quote.save
        # NotificationMailer.new_quote(@quote).deliver
        format.html do
          redirect_to quote_request_quote_path(quote_request, @quote), 
                      notice: 'Quote saved'
        end
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])

    respond_to do |format|
      if @quote.update_attributes(quote_params)
        format.html do
          redirect_to quote_request_quote_path(quote_request, @quote),
                      notice: 'Quote was successfully updated.'
        end
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end

  def quote
    Quote.find(params[:id])
  end

  def quote_request
    QuoteRequest.find(params[:quote_request_id])
  end

  def quote_params
    params.require(:quote).permit(:labor_hours, :oven_hours, :hourly_oven_price, :powder_pounds, :powder_price, :sandblasting_rate, :sandblasting_hours, :cost_of_business, :pricing_scale, :labor_rate, :sandblasting_media_multiplier)
  end
end

app/helpers/quotes_helper.rb
# frozen_string_literal: true

module QuotesHelper
  def us_states
    [
      %w[Alabama AL],
      %w[Alaska AK],
      %w[Arizona AZ],
      %w[Arkansas AR],
      %w[California CA],
      %w[Colorado CO],
      %w[Connecticut CT],
      %w[Delaware DE],
      ['District of Columbia', 'DC'],
      %w[Florida FL],
      %w[Georgia GA],
      %w[Hawaii HI],
      %w[Idaho ID],
      %w[Illinois IL],
      %w[Indiana IN],
      %w[Iowa IA],
      %w[Kansas KS],
      %w[Kentucky KY],
      %w[Louisiana LA],
      %w[Maine ME],
      %w[Maryland MD],
      %w[Massachusetts MA],
      %w[Michigan MI],
      %w[Minnesota MN],
      %w[Mississippi MS],
      %w[Missouri MO],
      %w[Montana MT],
      %w[Nebraska NE],
      %w[Nevada NV],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      %w[Ohio OH],
      %w[Oklahoma OK],
      %w[Oregon OR],
      %w[Pennsylvania PA],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      %w[Tennessee TN],
      %w[Texas TX],
      %w[Utah UT],
      %w[Vermont VT],
      %w[Virginia VA],
      %w[Washington WA],
      ['West Virginia', 'WV'],
      %w[Wisconsin WI],
      %w[Wyoming WY]
    ]
end
end

app/views/quotes/_form.html.haml
.row
  .col-sm-8
    = simple_form_for [quote_form.quote_request, quote_form.quote], html: { id: 'calculator-form' } do |f|
      .row.mb-3
        .col-sm-6
          = f.input :labor_hours,
                    placeholder: 'Estimated # of hours',
                    input_html: { data: { rate: quote_form.labor_rate } }
        .col-sm-6
          = f.input :labor_rate,
                    readonly: true,
                    input_html: { value: quote_form.quote.labor_rate || quote_form.labor_rate }
      .row.mb-3
        .col-sm-6
          = f.input :oven_hours, placeholder: 'Estimated # of hours'
        .col-sm-6
          = f.input :hourly_oven_price,
                    label: 'Oven size',
                    collection: quote_form.oven_sizes,
                    prompt: 'Select an oven size'
      .row.mb-3
        .col-sm-6
          = f.input :powder_pounds, label: 'Powder pounds', placeholder: 'Estimated # of lbs'
        .col-sm-6
          = f.input :powder_price,
                    collection: quote_form.powder_costs,
                    prompt: 'Select a powder price'
      .row.mb-3
        .col-sm-6
          = f.input :sandblasting_hours,
                    label: 'Sandblasting hours',
                    placeholder: 'Estimated # of lbs',
                    input_html: { data: { rate: quote_form.quote.sandblasting_rate || quote_form.sandblasting_rate } }
        .col-sm-6
          = f.input :sandblasting_rate,
                    readonly: true,
                    input_html: { value: quote_form.quote.sandblasting_rate || quote_form.sandblasting_rate }
      .row.mb-4
        .col-sm-6
          = f.input :sandblasting_media_multiplier,
                    readonly: true,
                    input_html: { value: quote_form.sandblasting_media_multiplier }
      .row.mt-3
        .col-lg-12.text-center.mb-2
          = f.input :cost_of_business, readonly: true, input_html: { value: quote_form.quote.cost_of_business }
          %label{ for: 'cost of business' } Cost Of Business
          %br/
          %input{ 'data-provide' => 'slider',
                  'data-slider-max' => '8',
                  'data-slider-min' => '0',
                  'data-slider-step' => '1',
                  'data-slider-ticks' => quote_form.cost_of_business_ticks,
                  'data-slider-ticks-labels' => quote_form.cost_of_business_labels,
                  'data-slider-tooltip' => 'hide',
                  'data-slider-value' => quote_form.cost_of_business_slider_location,
                  :name => 'cost-of-business',
                  :type => "integer" }
        .col-lg-12.text-center.mb-4
          = f.input :pricing_scale, readonly: true, input_html: { value: quote_form.quote&.pricing_scale }
          %label{ for: 'margin' } Pricing Scale
          %br/
          %input{ 'data-provide' => 'slider',
                  'data-slider-max' => '4',
                  'data-slider-min' => '0',
                  'data-slider-step' => '1',
                  'data-slider-ticks' => quote_form.margin_ticks,
                  'data-slider-ticks-labels' => quote_form.margin_labels,
                  'data-slider-tooltip' => 'hide',
                  'data-slider-value' => quote_form.margin_slider_location,
                  :name => 'margin',
                  :type => "integer"}/
      .row.mt-3
        .col-12
          = f.submit "Save quote", class: 'btn btn-success float-right'

  .col-sm-4
    %table.table.table-bordered
      %tbody
        %tr
          %td
            Coating Costs
          %td#coating_costs
            $
            %span 0.00
        %tr
          %td
            Sandblasting Costs
          %td#sandblasting_costs
            $
            %span 0.00
        %tr
          %td
            Total
          %td#total
            $
            %span 0.00

app/views/quotes/edit.html.haml
.container.contact
  %h1 Editing Quote
  = render 'form', quote_form: @quote_form

app/views/quotes/index.html.haml
.container.contact
  %h1 Listing quotes
  %table.table.table-bordered.table-striped
    %tr
      %th Status
      %th First name
      %th Last name
      %th Company
      %th Email
      %th Telephone
      %th Part description
      %th Assigned to
      %th
      %th
      %th
    - @quotes.each do |quote|
      - if quote.status == "New"
        %tr{:style => "background-color:#cccccc;"}
          - elsif quote.status == "Viewed"
            %tr{:style => "background-color:#ffff99;"}
              - elsif quote.status == "Submitted"
                %tr{:style => "background-color:#99ccff;"}
                  - elsif quote.status == "Won"
                    %tr{:style => "background-color:#ccffcc;"}
                      - elsif quote.status == "Lost"
                        %tr{:style => "background-color:#ff9999;"}
                          %td= quote.status
                          %td= quote.first_name
                          %td= quote.last_name
                          %td= quote.company_name
                          %td= quote.email
                          %td= quote.telephone
                          %td= quote.part_description
                          %td= quote.user ? quote.user.first_name : "Not assigned."
                          %td= link_to 'Show', quote
                          %td= link_to 'Edit', edit_quote_path(quote)
                          %td= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Quote', new_quote_path, class: "btn btn-special btn-color"

app/views/quotes/new.html.haml
.container
  %h1 Quote
  = render 'form', quote_form: @quote_form

app/views/quotes/show.html.haml
.container
  %h1 Quote #{@quote.id}
  %p
    %b Customer:
    #{ @quote.quote_request&.customer&.name }

  %table.table.table-bordered
    %tbody
      %tr
        %td Labor
        %td #{number_with_precision @quote.labor_hours, :precision => 2} (hours)
        %td $#{number_with_precision @quote.labor_rate, :precision => 2} ($/hour)
        %td 
      %tr
        %td Powder
        %td #{number_with_precision @quote.powder_pounds, :precision => 2} (lbs)
        %td $#{number_with_precision @quote.powder_price, :precision => 2}
        %td
      %tr
        %td Oven
        %td #{number_with_precision @quote.oven_hours, :precision => 2} (hours)
        %td $#{number_with_precision @quote.hourly_oven_price, :precision => 2} ($/hour)
        %td
      %tr
        %td Coating Costs
        %td
        %td
        %td $#{number_with_precision @quote.coating_costs, :precision => 2}
      %tr
        %td Sandblasting
        %td #{number_with_precision @quote.sandblasting_hours, :precision => 2}
        %td $#{number_with_precision @quote.sandblasting_rate, :precision => 2}
        %td $#{number_with_precision @quote.total_sandblasting_cost, :precision => 2}
      %tr
        %th Total
        %td
        %td
        %th $#{number_with_precision @quote.total, :precision => 2}

  = link_to 'View quote request', @quote.quote_request
  | #{link_to 'Edit', edit_quote_request_quote_path(@quote.quote_request, @quote)}