config/routes.rb
# frozen_string_literal: true

Cpc::Application.routes.draw do

  constraints AdminConstraint do
    mount Flipper::UI.app(Flipper) => '/flipper'
  end

  constraints InternalUserConstraint do
    root to: 'internal/dashboards#show'
  end

  constraints CustomerUserConstraint do
    resources :customers do
      resources :work_orders, only: [:show], controller: 'customers/work_orders'
    end

    root to: 'customers/dashboards#show'
  end

  resources :boxes
  resources :colors
  resources :contacts
  resources :customers do
    resources :attachments, only: [:create]
    resources :contacts
    resources :notes
    resources :users, controller: 'customers/users'
      resources :work_orders
  end
  resources :manufacturers
  resources :notes
  resources :powders
  resources :quote_requests do
    resources :notes

    member do
      get 'mark_as_viewed'
      get 'mark_as_submitted'
      get 'mark_as_won'
      get 'mark_as_lost'
    end

    collection do
      get 'calculator'
      get 'sand_blasting_quote_calculator'
    end

    resources :quotes
  end
  resources :quote_request_attachments
  resource :quote_request_conversions, only: [:create]
  resources :service_schedules
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/thank_you'
  devise_for :users
  resources :users
  resources :work_orders do
    resources :attachments, only: [:create]
    resources :notes

    collection do
      get :workflow
    end

    member do
      post :quality_assurance_approval
      put :mark_completed
    end
  end
  resources :work_order_schedules

  root to: 'static_pages#home'
end

app/models/box.rb
# frozen_string_literal: true

class Box < ApplicationRecord
  belongs_to :powder

  validates  :powder, presence: true
  validate :original_weight_not_changed

  after_save :check_for_low_weight_reminder

  has_paper_trail

  def percent_left
    ((weight.to_f / original_weight.to_f) * 100).to_i
  end

  private

  def original_weight_not_changed
    errors.add(:original_weight, "Can't change original weight after a box has been added.") if original_weight_changed? && persisted?
  end

  def check_for_low_weight_reminder
    if send_low_powder_reminder?
      NotificationMailer.low_powder_notification(powder).deliver
      powder.update_attribute :last_weight_reminder, Date.today
    end
  end

  def send_low_powder_reminder?
    (powder.total_weight <= powder.reminder_weight) && (powder.last_weight_reminder.nil? || powder.last_weight_reminder < Date.today - 4.days)
  end
end

app/controllers/boxes_controller.rb
# frozen_string_literal: true

class BoxesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_box, only: %i[show edit update destroy]

  respond_to :html

  def index
    @boxes = Box.all
    respond_with(@boxes)
  end

  def show
    respond_with(@box)
  end

  def new
    @box = Box.new
    respond_with(@box)
  end

  def edit; end

  def create
    @box = Box.new(box_params)
    @box.save
    respond_with(@box.powder)
  end

  def update
    @box.update(box_params)
    respond_with(@box.powder)
  end

  def destroy
    @box.destroy
    respond_with(@box)
  end

  private

  def set_box
    @box = Box.find(params[:id])
  end

  def box_params
    params.require(:box).permit(:powder_id, :weight, :original_weight)
  end
end

app/views/boxes/_form.html.haml
= simple_form_for(@box) do |f|
  = f.error_notification
  .form-inputs
    - if params[:powder_id]
      = f.association :powder, label_method: :list_name, selected: params[:powder_id], input_html: { class: 'chosen' }
    - else
      = f.association :powder, label_method: :list_name, input_html: { class: 'chosen' }
    = f.input :original_weight, placeholder: 'standard weight of box when received'
    = f.input :weight, hint: 'in lbs (round down to the nearest pound)'
  .form-actions
    = f.button :submit, class: 'btn btn-lg btn-success'

app/views/boxes/edit.html.haml
.container
  .row
    .col-sm-4
      %h1 Editing box
      %p.alert.alert-warning.mt-3.mb-4
        To update the weight
        %strong enter the new total weight
        of the box and
        = succeed "." do
          %strong click 'Update Box'
      = simple_form_for(@box) do |f|
        = f.error_notification
        .form-inputs
          = f.association :powder, label_method: :list_name, disabled: true, input_html: { class: 'chosen' }
          = f.input :original_weight, placeholder: 'standard weight of box when received', disabled: true
          = f.input :weight, hint: 'in lbs (round down to the nearest pound)'
        .form-actions
          = f.button :submit, class: 'btn btn-lg btn-success'

app/views/boxes/index.html.haml
%h1 Listing boxes
%table
  %thead
    %tr
      %th Powder
      %th Weight
      %th{:colspan => "3"}
  %tbody
    - @boxes.each do |box|
      %tr
        %td= box.powder_id
        %td= box.weight
        %td= link_to 'Show', box
        %td= link_to 'Edit', edit_box_path(box)
        %td= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Box', new_box_path

app/views/boxes/new.html.haml
= title 'New Box'
.container
  %h1 New box
  .row
    .col-sm-4
      = render 'form'

app/views/boxes/show.html.haml
.container
  .row
    .col-sm-4
      %h1 Box
      %p
        %strong Powder Type:
        = link_to @box.powder.list_name, @box.powder
      %p
        %strong Original Weight:
        = @box.original_weight
      %p
        %strong Weight:
        = @box.weight
      %p
        = link_to "Edit", edit_box_path
        | #{link_to "Powder Inventory", powders_path}